apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-config
spec:
  selector:
    app: spring-k8s-config
  type: NodePort
  ports:
    - name: spring-k8s-config
      port:  8080
      targetPort: 8080